FROM node:alpine as builder
WORKDIR /app

# ARG VITE_BACKEND_URL
# ARG VITE_TOSSPAYMENTS_TEST_CLIENT_KEY
# ARG VITE_TOSSPAYMENTS_CLIENT_KEY
# ARG VITE_SENTRY_DNS

# ENV VITE_BACKEND_URL="test"
# ENV VITE_TOSSPAYMENTS_TEST_CLIENT_KEY $VITE_TOSSPAYMENTS_TEST_CLIENT_KEY
# ENV VITE_TOSSPAYMENTS_CLIENT_KEY $VITE_TOSSPAYMENTS_CLIENT_KEY
# ENV VITE_SENTRY_DNS $VITE_SENTRY_DNS

COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]